### ISSUE TITLE
configure devign

### ISSUE THREAD

**Issue by KSB21ST** [epicosy/devign#11]
Hi, I am currently trying to run devign.
However, I don't seem to find the '/data/model' folder as mentioned in README.md > Setup. 
Also, I tried configure with

$python3 configs.py

But it does not seem to work.
What can I do for the missing /data/model folder?

**Comment by epicosy** [comment]
Hi, @KSB21ST. The repository does not include the model, you have to train a model with the input dataset. First, you have to set up the project, by configuring and creating the "paths" for the output files in the configurations file 'configs.json'. Then you have to execute the baseline workflow, create -> embed -> process, to generate the input files for the model training. You can find more details about those tasks in the README.md under the section Baseline.
