### ISSUE TITLE
Cannot parse using the latest joern

### ISSUE THREAD

**Issue by faysalhossain2007** [epicosy/devign#14]
Can you tell us which version of the Joern you used to generate the CPG?

Currently I am getting error in the following line: 

```
    joern_parse_call = subprocess.run(["./" + joern_path + "joern-parse", input_path, "--out", output_path + out_file],
                                      stdout=subprocess.PIPE, text=True, check=True)
```

That's because in the latest Joern they use the following code to export cpg to a directory:

```
joern-parse /src/directory
joern-export --repr pdg --out outdir
```
I tried older Joern version. But I faced other problems there: https://github.com/epicosy/devign/issues/3#issuecomment-1057844454

**Comment by Vinothini-G** [comment]
Instead of --out, you can try --output. Hope it helps!

**Comment by brian5121** [comment]
Hello,
I am getting the same error after replacing --out with --output. Any suggestions?

**Comment by faysalhossain2007** [comment]
https://github.com/epicosy/devign/issues/17#issue-1291889668
