### ISSUE TITLE
Create task cannot to implement

### ISSUE THREAD

**Issue by Sos-sc2** [epicosy/devign#6]
I want to create my dataset but failed. Do i miss some dependency?
![微信图片_20201105152410](https://user-images.githubusercontent.com/52203915/98210292-3bfd0780-1f38-11eb-92e8-dfde6656bebb.png)

**Comment by epicosy** [comment]
Hi @Sos-sc2,  I think that this closed issue #3 may help you. Let me know if you managed to make it work.

**Comment by shan12138** [comment]
> I want to create my dataset but failed. Do i miss some dependency?
> ![微信图片_20201105152410](https://user-images.githubusercontent.com/52203915/98210292-3bfd0780-1f38-11eb-92e8-dfde6656bebb.png)

Hello, I encountered the same problem as yours. Have you solved it now? Is it because of the joer-cli version or some other reason? If you solve it, I hope you can reply to me. Thank you very much.
